services:
    laravel-upwork.test:
        build:
            context: .
            target: development
            args:
                # UID and GID must be set as environment variables on the host machine
                USER_ID: $UID
                GROUP_ID: $GID
        image: serversideup/php:8.3-fpm-nginx
        restart: unless-stopped
        ports:
            - '${APP_PORT:-10999}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:        
            PUID : $UID
            PGID : $GID
            PHP_OPCACHE_ENABLE: 0
            # Laravel variables
            AUTORUN_ENABLED: "true"
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost/healthcheck"] # Ensure your route exists or use /
            interval: 10s
            timeout: 5s
            retries: 3

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail

networks:
    sail:
        driver: bridge

volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local